on:
  push:
  release:
    types:
      - published
      - created

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: abc
        run: |
          echo "NAME=Debdut" >> $GITHUB_ENV
          
  show:
    runs-on: ubuntu-latest
    needs: [show_payload]
    steps:
      - name: efg
        run: echo ${{ env.NAME }}
