on:
#   push:
  release:
    types:
      - published
#       - created

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: abc
        run: |
          echo "NAME=Debdut" >> $GITHUB_ENV
          
  show:
    runs-on: ubuntu-latest
    needs: [show_payload]
    steps:
      - name: efg
        run: echo ${{ env.NAME }}
        
      - name: show latest tag
        run: |
          git -c 'versionsort.suffix=-' ls-remote -t --exit-code --refs --sort=-v:refname \
            https://github.com/debdutdeb/action '*' \
            | sed -En '1!q;s/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/gp'
          curl https://api.github.com/repos/debdutdeb/action/releases/latest | grep tag_name
