on:
  push:
  release:
    types:
      - published
      - created

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: show gittag
        run: echo $GITHUB_REF $GITHUB_REF_NAME
        
      - name: test workflow function
        run: |
          echo "::setFailed::failed"
