on:
  push:
  release:
    types:
      - published
      - created

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: create archive
        run: |
          mkdir test
          touch test/{1,2,3,4}
          tar czvf arc.tar.gz test
          echo "source=$(realpath arc.tar.gz)" >> $GITHUB_ENV
      
      - name: push
        uses: debdutdeb/rc4community.deploy.action@main
        with:
          remote_host: ${{ secrets.IP }}
          ssh_private_key: ${{ secrets.KEY }}
          source: ${{ env.source }}
          destination: '/tmp/'
