on:
  push:
  release:
    types:
      - published
#       - created

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: abc
        run: |
          echo $GITHUB_REPOSITORY
          
  
