on:
  push:

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: Show base
        uses: debdutdeb/action@main
        with:
          key: base
      - name: Show base repo
        uses: debdutdeb/action@main
        with:
          key: base.repo
          
      - name: Show repository
        uses: debdutdeb/action@main
        with:
          key: repository
