on:
  push:
  release:
    types:
      - published
      - created

jobs:
  show_payload:
    runs-on: ubuntu-latest
    name: A job to show payload data
    steps:
      - name: create file
        run: echo "Hello World!" > hello.txt
      
      - name: push
        uses: debdutdeb/rc4community.deploy.action@test
        with:
          remote_host: ${{ secrets.IP }}
          ssh_private_key: ${{ secrets.KEY }}
          source: './hello.txt'
          destination: '/tmp'
